---
namespace: "kalenpeterson"
description: Solarwinds Orion IPAM record creator
name: "orion_ipam"
version: "1.1.2"
readme: "README.md"
authors:
    - "Kalen Peterson"
    - "Callie Howard"
license:
    - "MIT"
tags:
    - solarwinds
    - ipam
    - orion
    - collection
repository: "https://github.com/kalenpeterson/ansible-orion"
